// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load backend/.env explicitly (cwd is usually the backend folder when you run prisma/nest)
// `override: true` so backend/.env wins over a stale machine-level DATABASE_URL (common P1001 / wrong-DB bugs).
config({ path: path.resolve(process.cwd(), ".env"), override: true });

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl?.trim()) {
  throw new Error(
    "DATABASE_URL is missing. Add it to backend/.env (see prisma.config.ts).",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    url: databaseUrl,
  },
});
